# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Top 10 FAIR Data & Software Things"
description:        "Description of Top 10..."

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
url:                "//https://librarycarpentry.org/Top-10-FAIR/"
author:             "librarycarpentry"
twitter:
  username:         "LibCarpentry"
#facebook:
#  app_id:           1234
#    publisher:      1234

# URL
baseurl:            "https://librarycarpentry.org/Top-10-FAIR/"
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title/

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "About"
    href:           "//librarycarpentry.org/Top-10-FAIR/about"
  - name:           "Download"
    href:           "//github.com/librarycarpentry/Top-10-FAIR/releases"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-seo-tag
